"""
logic/rebalancer.py
Threshold rebalancing execution logic.

This module acts as the decision engine. It compares the optimal asset allocation 
generated by the eigensolver against the user's current portfolio state, applying 
a strict drift threshold to minimize unnecessary turnover, slippage, and tax events.
"""

from typing import Dict, List
from core.state import PortfolioState, TradeRecommendation

def generate_trade_actions(
    current_state: PortfolioState,
    optimal_allocation: Dict[str, int],
    drift_threshold_pct: float = 5.0
) -> List[TradeRecommendation]:
    """
    Compares the current portfolio against the target allocation and generates 
    actionable trades, filtering out any asset adjustments that do not breach 
    the specified drift threshold.
    
    Args:
        current_state (PortfolioState): The validated current state of the portfolio.
        optimal_allocation (Dict[str, int]): The target integer share counts outputted 
                                             by the exact eigensolver.
        drift_threshold_pct (float): The minimum percentage drift required to trigger 
                                     a trade. Defaults to 5.0%.
                                     
    Returns:
        List[TradeRecommendation]: A list of actionable, threshold-filtered trades.
    """
    recommended_trades = []
    
    # Create a unified set of all tickers present in either the current or optimal state
    all_tickers = set(current_state.positions.keys()).union(set(optimal_allocation.keys()))
    
    for ticker in all_tickers:
        # Extract current state metrics (default to 0 if we don't currently hold it)
        current_position = current_state.positions.get(ticker)
        current_shares = current_position.shares if current_position else 0
        
        # Ensure we have a price to evaluate the trade (critical for nominal value)
        # If the asset isn't in the current portfolio, we must fetch its price 
        # (Assuming the UI or earlier state hydrated a master price list, but for 
        # safety, we pull it from the position object. In a full implementation, 
        # a global price dict is passed or accessed here).
        price = current_position.price if current_position else 0.0 
        
        # Extract target state metrics
        target_shares = optimal_allocation.get(ticker, 0)
        
        # Skip if no change is mathematically optimal
        if current_shares == target_shares:
            continue
            
        # Instantiate the domain model
        trade = TradeRecommendation(
            symbol=ticker,
            current_shares=current_shares,
            target_shares=target_shares,
            price=price
        )
        
        # Apply Threshold Logic
        # New positions inherently have 100% drift (0 to N shares)
        # Liquidations inherently have 100% drift (N to 0 shares)
        if trade.drift_percentage >= drift_threshold_pct:
            recommended_trades.append(trade)
            
    # Sort trades by nominal value magnitude (largest trades first)
    recommended_trades.sort(key=lambda t: abs(t.trade_value), reverse=True)
            
    return recommended_trades